services:
  goodhamburger.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goodhamburger-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=goodhamburger;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  goodhamburger.blazor:
    build:
      context: .
      dockerfile: Dockerfile.Blazor
    container_name: goodhamburger-blazor
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ApiSettings__BaseUrl: http://goodhamburger.api:8080
    ports:
      - "8081:8080"
    depends_on:
      - goodhamburger.api

  postgres:
    image: postgres:16-alpine
    container_name: goodhamburger-postgres
    environment:
      POSTGRES_DB: goodhamburger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - goodhamburger_postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goodhamburger"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  goodhamburger_postgres_data: