# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY GoodHamburger.Blazor/GoodHamburger.Blazor.csproj GoodHamburger.Blazor/

RUN dotnet restore GoodHamburger.Blazor/GoodHamburger.Blazor.csproj

COPY . .

RUN dotnet publish GoodHamburger.Blazor/GoodHamburger.Blazor.csproj \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "GoodHamburger.Blazor.dll"]